name: Build Master Branch

# Master Branch Push 시 아래 실행
on:
  push:
    branches: [ "Master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Java 17 세팅
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # gradlew 실행 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 빌드 전 clean
    - name: Clean Build
      run: ./gradlew clean

    # 전체 빌드 시작
    - name: Build with Gradle
      run: ./gradlew build

    # Debug APK 업로드
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: debug
        path: ./app/build/outputs/apk/debug/*.apk

